# -*- coding: utf-8 -*-
"""Lagos_airports_review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_s0DCGYLV6sIU9Y9xqIOQMfIsTk7zvn
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

base_url = "https://www.airlinequality.com/airport-reviews/lagos-airport/"
pages = 10  # Number of pages to scrape
page_size = 100  # Number of reviews per page

reviews = []
df = pd.DataFrame()

for i in range(1, pages + 1):

    rating = []
    category = []

    print(f"Scraping page {i}")

    # Create URL to collect links from paginated data
    url = f"{base_url}/page/{i}/?sortby=post_date%3ADesc&pagesize={page_size}"

    # Collect HTML data from this page
    response = requests.get(url)

    # Parse content
    content = response.content
    parsed_content = BeautifulSoup(content, 'html.parser')

    for para in parsed_content.find_all("div", {"class": "text_content"}):
        reviews.append(para.get_text())

    for para2 in parsed_content.find_all("div", {"class" : "review-stats"}):
        for para3 in para2.find_all('td',{'class' : 'review-value'}):
            rating.append(para3.get_text())
        recomend = rating[-1]
        rating = rating[:-1]

        for para4 in para2.find_all('td',{'class' : 'review-rating-stars stars'}):
            para5 = len(para4.find_all('span', {'class' : 'star fill'}))
            rating.append(para5)
        rating.append(recomend)

        for para6 in para2.find_all('td',{'class' : 'review-rating-header'}):
            category.append(para6.get_text())

        # Create a temporary DataFrame from the dictionary and concatenate with the main DataFrame
        data_dict = pd.DataFrame([rating], columns=category)
        df = pd.concat([df, data_dict], ignore_index=True)

        rating = []
        category = []

    print(f"   ---> {len(reviews)} total reviews")

df["reviews"] = reviews

# Display the DataFrame
print(df.head())

print(df.iloc[15])

# Store the DataFrame in a CSV file
df.to_csv('lagos_airport_reviews.csv', index=False)

# Display the DataFrame
print(df.head())

